// <auto-generated />
using System;
using HarbourOps.Adapters.EfSqlite.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarbourOps.Adapters.EfSqlite.Persistence.Migrations
{
    [DbContext(typeof(HarbourOpsDbContext))]
    partial class HarbourOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HarbourOps.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HarbourOps.Domain.Bookings.ServiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "REEFER-MON",
                            Description = "Temperature monitoring and daily check for refrigerated containers.",
                            IsActive = true,
                            Name = "Reefer Container Monitoring"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "VGM-WEIGH",
                            Description = "Certified container weighing for export compliance.",
                            IsActive = true,
                            Name = "Verified Gross Mass Weighing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "CUSTOMS-HOLD",
                            Description = "Special handling for containers under customs inspection.",
                            IsActive = true,
                            Name = "Customs Hold Handling"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "PRIORITY-GATE",
                            Description = "Priority truck gate processing during peak terminal hours.",
                            IsActive = true,
                            Name = "Priority Gate Appointment"
                        });
                });

            modelBuilder.Entity("HarbourOps.Domain.Bookings.Booking", b =>
                {
                    b.OwnsMany("HarbourOps.Domain.Bookings.BookingLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("BookingId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ServiceItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServiceName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("BookingLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("HarbourOps.Domain.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("BookingLineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("UnitPriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("UnitPriceCurrency");

                                    b2.HasKey("BookingLineId");

                                    b2.ToTable("BookingLines");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingLineId");
                                });

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HarbourOps.Domain.Bookings.ServiceItem", b =>
                {
                    b.OwnsOne("HarbourOps.Domain.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("ServiceItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("ServiceItemId");

                            b1.ToTable("ServiceItems");

                            b1.WithOwner()
                                .HasForeignKey("ServiceItemId");

                            b1.HasData(
                                new
                                {
                                    ServiceItemId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    Amount = 125m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    ServiceItemId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    Amount = 85m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    ServiceItemId = new Guid("33333333-3333-3333-3333-333333333333"),
                                    Amount = 210m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    ServiceItemId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    Amount = 60m,
                                    Currency = "GBP"
                                });
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
